services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - WORKSPACES:${WORKSPACES}
      - ..:${WORKSPACES}/${COMPOSE_PROJECT_NAME}
      - XDG_CONFIG_HOME:${XDG_CONFIG_HOME}
      - XDG_CACHE_HOME:${XDG_CACHE_HOME}
      - XDG_DATA_HOME:${XDG_DATA_HOME}
      - XDG_STATE_HOME:${XDG_STATE_HOME}
volumes:
  WORKSPACES:
  XDG_CONFIG_HOME:
  XDG_CACHE_HOME:
  XDG_DATA_HOME:
  XDG_STATE_HOME:
