name: "Renovate"

on:
  schedule:
    - cron: "0 0 7,21 * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Renovate
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: pnpm renovate
          env: GITHUB_TOKEN=${{ secrets.RENOVATE_TOKEN }}
